### ISSUE TITLE
Failed to deploy bower package

### ISSUE THREAD

**Issue by NorbertSandor** [webjars/webjars#1197] opened 2015-09-09 20:49 UTC
Deploying jquery-2.1.4 failed:

> Failed!
> {"status":"Sync Failed","messages":"[Failed to promote repository: orgwebjars-7101. Server response:\n could not parse response from server., Dropping existing partial staging repository.]"}
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
>             
> Created BinTray Package
> Converted project licenses
> Created Bower WebJar
> Fetched Bower zip
> Generated POM
> Converted dependencies to Maven
> Got Bower info
> Determined Artifact Name: jquery
> Starting Deploy

**Comment by NorbertSandor** [comment] 2015-09-09 20:52
Similar issue with: vertx3-eventbus-client 3.0.0

**Comment by jamesward** [comment] 2015-09-09 21:07
Duplicate of #1196

**Closed by jamesward** 2015-09-09 21:07 UTC
