### ISSUE TITLE
Failed to create webjar for iron-elements (part of Polymer)

### ISSUE THREAD

**Issue by ptxmac** [webjars/webjars#1126] opened 2015-07-12 14:28 UTC
Failed! Could not convert npm version to maven for: iron-validator-behavior PolymerElements/iron-validator-behavior#^1.0.0 If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Got Bower info Starting Deploy

**Comment by jamesward** [comment] 2015-07-12 14:43
Duplicate of #1044.

**Closed by jamesward** 2015-07-12 14:43 UTC
