### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by JonasVon** [webjars/webjars#1847] opened 2019-04-03 02:27 UTC
![image](https://user-images.githubusercontent.com/34496500/55448580-daa5e180-55fa-11e9-8b4c-9ba2293856e1.png)

**Comment by jamesward** [comment] 2019-04-03 03:13
I thought this was something due to Maven Central.  But it looks like a bug.  I'm investigating.  Sorry for the hassle.  Duplicate of #1845

**Closed by jamesward** 2019-04-03 03:13 UTC
