### ISSUE TITLE
Styling is broken on webjars.org and adding an npm is not possible because of that

### ISSUE THREAD

**Issue by joost-de-vries** [webjars/webjars#1624] opened 2017-07-07 09:28 UTC
The CDN that should provide bootstrap gives 404s. 
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1859426/27952076-58fc3e64-6307-11e7-8773-aed158208bad.png">

**Comment by joost-de-vries** [comment] 2017-07-07 11:17
It's working again. Apparently a glitch of the CDN.

**Comment by jamesward** [comment] 2017-07-07 14:11
This was caused by #1623 so I rolled back the release.  I do need to fix this.

**Comment by jamesward** [comment] 2017-07-08 19:30
This was fixed by https://github.com/webjars/webjars/commit/903e0fe39fa8db3430b81625581fdea38d3501ee

**Closed by jamesward** 2017-07-08 19:30 UTC
