### ISSUE TITLE
Web site very slow

### ISSUE THREAD

**Issue by evictor** [webjars/webjars#1585] opened 2017-05-01 03:10 UTC
Not sure where I should file this—if this is the wrong place, LMK where to put and I will refile.

The webjars.org site is extremely slow, more or less unusable. The culprit is probably the giant list of packages feeding whatever JS rendering framework and the big ass table/list.

The first step to fix would be to implement some clientside pagination such that the JS framework being used doesn't have to ever try to render that many table rows.

If you point me in the direction of the Web site source I would be happy to submit the changes myself.

**Comment by jamesward** [comment] 2017-05-01 03:28
Yeah, we need to get this fixed.  It isn't too bad in Chrome on a MacBook Air. But I think it is pretty slow on Firefox and maybe other hardware.

Duplicate of #1327

**Closed by jamesward** 2017-05-01 03:28 UTC
