### ISSUE TITLE
NPM Webjars incorrectly cannot find LICENSE.md for async-validator

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1536] opened 2017-01-04 11:01 UTC
> Failed!
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: git@github.com:yiminghe/async-validator
The acceptable open source software licenses are at: https://bintray.com/docs/api/#_footnote_1
The provided licenses were: 
This problem will likely need to be resolved by working with the library maintainers directly.
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

> Got NPM info
Determined Artifact Name: async-validator
Starting Deploy

Repo is here https://github.com/yiminghe/async-validator and the pull request which adds async-validator is here https://github.com/yiminghe/async-validator/pull/27

**Comment by jamesward** [comment] 2017-01-04 16:07
Hmmm... Their `package.json` is wrong according to [the spec](https://docs.npmjs.com/files/package.json#license) but you are right that the `LICENSE.md` should have worked.  I'll investigate.

**Comment by mdedetrich** [comment] 2017-01-04 16:12
It has worked for their other projects (some of which also have an invalid `package.json`) so it sounds like its a corner case

**Comment by jamesward** [comment] 2017-01-04 16:32
I just tried a deploy with `1.6.8` and it resolved the license.  So maybe this was a transient issue.  Closing for now, but let me know if the problem is still happening with a different version.

**Comment by mdedetrich** [comment] 2017-01-04 17:21
@jamesward Yeah its v 1.0.0 that is failing, and its the specific version that I need

**Comment by jamesward** [comment] 2017-01-04 18:57
We could fall back to looking for a license at the HEAD if we can't find one on a tag.  I thought we did that already though.  I'll investigate.

**Closed** 2017-01-07 19:00 UTC
Labels: bug

**Comment by jamesward** [comment] 2017-01-07 19:09
The changes from #1538 have been deployed and I was able to deploy that package:
```
GroupID = org.webjars.npm
ArtifactID = async-validator
Version = 1.0.0
```
