### ISSUE TITLE
is-extglob

### ISSUE THREAD

**Issue by dhakehurst** [webjars/webjars#1713] opened 2018-02-05 15:47 UTC
Got the source URL: https://github.com/micromatch/is-extglob
Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Deploying org.webjars.npm is-extglob 2.1.1
Failed!
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/ben-eb/caniuse-lite.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: CC-BY-4.0

**Comment by jamesward** [comment] 2018-02-05 16:30
Duplicate of #1347

**Closed by jamesward** 2018-02-05 16:30 UTC
