### ISSUE TITLE
Timeouts on deploying

### ISSUE THREAD

**Issue by morpheus-87** [webjars/webjars#1654] opened 2017-09-12 09:06 UTC
Many times, when I try to deploy a new webjar or a new version of an existing one, I get timeouts:

```
Failed!
Read timeout to bintray.com/108.168.194.93:443 after 120000 ms
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
```

**Comment by morpheus-87** [comment] 2017-09-12 09:13
Another message, I have seen sometimes:

```
Failed!
{"status":"Sync Failed","messages":"[Failed to close repository: orgwebjars-32459. Server response:\n <nexus-error>\n <errors>\n <error>\n <id>*<\u002fid>\n <msg>Unhandled: Repository: orgwebjars-32459 has invalid state: closed<\u002fmsg>\n <\u002ferror>\n <\u002ferrors>\n<\u002fnexus-error>, Dropping existing partial staging repository.]"}
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
```

**Comment by jamesward** [comment] 2017-10-09 17:43
Duplicate of #1648

**Closed by jamesward** 2017-10-09 17:43 UTC
