### ISSUE TITLE
Failed deploy (@angular/material)

### ISSUE THREAD

**Issue by danoliv** [webjars/webjars#1651] opened 2017-08-30 13:27 UTC
Failed!
Read timeout to bintray.com/75.126.118.184:443 after 120000 ms
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Published BinTray Version
Signed BinTray Assets
Published BinTray Assets
Created BinTray Version
Created BinTray Package
Created NPM WebJar
Fetched NPM zip
Generated POM
Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Got NPM info
Determined Artifact Name: angular__material
Deploying org.webjars.npm @angular/material 2.0.0-beta.10
Starting Deploy

**Comment by doonot** [comment] 2017-08-30 14:04
Same here

**Comment by jamesward** [comment] 2017-08-30 15:21
Duplicate of #1648

**Closed by jamesward** 2017-08-30 15:21 UTC
