### ISSUE TITLE
Can't deploy bootstrap-timepicker 0.2.6 from bower

### ISSUE THREAD

**Issue by dominicpezzuto** [webjars/webjars#1491] opened 2016-10-17 18:36 UTC
Failed! https://raw.githubusercontent.com/mmonteleone/jquery.autotype/master/jquery.autotype.js: https://raw.githubusercontent.com/mmonteleone/jquery.autotype/master/jquery.autotype.js/info/refs?service=git-upload-pack not found If you feel you have reached this failure in error, please file an issue: 

https://github.com/webjars/webjars/issues  Resolved Licenses Got Bower info Determined Artifact Name: bootstrap-timepicker 
Starting Deploy
Deploy!

**Comment by jamesward** [comment] 2016-10-26 06:28
The problem is that they a specifying a dependency on a file in a git repo:
https://github.com/jdewit/bootstrap-timepicker/blob/v0.2.6/bower.json#L13

I don't think that is spec compliant:
https://github.com/bower/spec/blob/master/json.md#dependencies

So I think this should be fixed upstream.

**Closed by jamesward** 2016-10-26 06:28 UTC
