### ISSUE TITLE
fbjs has nonexistent dependency

### ISSUE THREAD

**Issue by mdgeek** [webjars/webjars#1619] opened 2017-06-26 20:06 UTC
fbjs depends on fbjs-css-vars which for some reason no longer exists.

**Comment by jamesward** [comment] 2017-06-26 20:17
Artifacts can't be removed so perhaps `fbjs-css` never existed?  Did you try to deploy it via http://webjars.org?

**Comment by mdgeek** [comment] 2017-06-26 21:23
Failed!

JsResultException(errors:List((,List(ValidationError(List(Predicate does not hold for https://www.npmjs.com/package/fbjs-css-vars),WrappedArray()))), (/repository/url,List(ValidationError(List(error.path.missing),WrappedArray())))))

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

 

Determined Artifact Name: fbjs-css-vars

Deploying org.webjars.npm fbjs-css-vars 1.0.0

**Comment by mdgeek** [comment] 2017-06-26 21:37
It looks to me like this isn’t a real artifact.  I think it is part of the fbjs package.  The build used to work fine.  Perhaps the fbjs artifact was redeployed at some point with the bogus dependency added.

 

From: Doug Martin <docanorak@gmail.com>
Date: Monday, June 26, 2017 at 5:23 PM
To: webjars/webjars <reply@reply.github.com>
Subject: Re: [webjars/webjars] fbjs has nonexistent dependency (#1619)

 

 

Failed!

JsResultException(errors:List((,List(ValidationError(List(Predicate does not hold for https://www.npmjs.com/package/fbjs-css-vars),WrappedArray()))), (/repository/url,List(ValidationError(List(error.path.missing),WrappedArray())))))

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

 

Determined Artifact Name: fbjs-css-vars

Deploying org.webjars.npm fbjs-css-vars 1.0.0

**Comment by jamesward** [comment] 2017-06-27 00:20
What version of `fbjs` are you trying?  I'm not seeing the dep on `fbjs-css-vars` in the latest: https://repo1.maven.org/maven2/org/webjars/npm/fbjs/0.1.0-alpha.12/fbjs-0.1.0-alpha.12.pom

**Comment by mdgeek** [comment] 2017-06-27 00:26
That’s not the latest.  The latest is 0.9.0-alpha.2

 

This is a transitive dependency via the ReactJS webjars.

**Comment by jamesward** [comment] 2017-06-27 01:08
Whoops.  You're right: https://repo1.maven.org/maven2/org/webjars/npm/fbjs/0.9.0-alpha.2/fbjs-0.9.0-alpha.2.pom

Looking into this...

**Comment by jamesward** [comment] 2017-06-27 01:12
Strange...  That version doesn't exist in git: https://github.com/facebook/fbjs/tags

**Comment by jamesward** [comment] 2017-06-27 01:14
But does exist on NPM: https://registry.npmjs.org/fbjs/0.9.0-alpha.2

**Comment by jamesward** [comment] 2017-06-27 01:21
And the dependency `fbjs-css-vars` does exist in NPM: https://registry.npmjs.org/fbjs-css-vars

But as you discovered it can't be deployed because the source repo can't be determined from metadata.  This is a requirement from BinTray to do the deployment.

Once #1604 is fixed then we can do the deployment but we'd need to know the source repo.  And I can't seem to find it for this package.  So I'm going to close this for now.  Until we find a way to deploy this you'll need to exclude that transitive dependency in your package manager.

**Closed by jamesward** 2017-06-27 01:21 UTC
Labels: waitingoninfo

**Comment by mdgeek** [comment] 2017-06-27 01:45
The problem is you can’t exclude a transitive dependency that does not exist.  I don’t believe the artifact is real.  I think its presence as a dependency is in error.  When I review the ReactJS dependencies in a working Node project, fbjs appears, fbjs-css-vars does not.  It needs to be removed from the pom.xml in the fbjs webjar.

**Comment by jamesward** [comment] 2017-06-27 01:53
You should be able to exclude a dependency from being resolved.  But instructions differ depending on your build tool.  The `fbjs` package does have a dependency on `fbjs-css-vars` which does exist on NPM.  The problem is that the `fbjs-css-vars` can't be deployed via NPM WebJars because of the missing source repo metadata.

**Comment by jamesward** [comment] 2017-07-11 14:32
I recently added a way to manually override the repo url so I was able to deploy `fbjs-css-vars` - see #1625

**Comment by mdgeek** [comment] 2017-07-11 15:31
Thanks, James.
