### ISSUE TITLE
Webjar request: @angular/**

### ISSUE THREAD

**Issue by aidenweatherby** [webjars/webjars#1402] opened 2016-05-27 22:07 UTC
Currently webjar site is not deploying because it cannot find a repository in the package, see error below.

Failed! The source repository for @angular/common 2.0.0-rc.1 could not be determined but is required to published to Maven Central. This will need to be fixed in the project's package metadata. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: angular__common Starting Deploy

Could we please get the below modules installed ?

"@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1"

**Comment by jamesward** [comment] 2016-05-27 22:16
Duplicate of #1399

**Closed by jamesward** 2016-05-27 22:16 UTC
