### ISSUE TITLE
Unable to deploy https://github.com/tastejs/todomvc-app-css

### ISSUE THREAD

**Issue by kumarshantanu** [webjars/webjars#1612] opened 2017-06-13 17:03 UTC
The project https://github.com/tastejs/todomvc-app-css has CC BY 4.0 license, as mentioned in the README and in the `package.json` file. This seems compatible with CC0 as listed at https://bintray.com/docs/api/#_footnote_1 - deployment log is below:

```
Failed!
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/tastejs/todomvc-app-css
The acceptable open source software licenses are at: https://bintray.com/docs/api/#_footnote_1
The provided licenses were: CC-BY-4.0
This problem will likely need to be resolved by working with the library maintainers directly.
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Got NPM info
Determined Artifact Name: github-com-tastejs-todomvc-app-css
Deploying org.webjars.npm https://github.com/tastejs/todomvc-app-css v2.1.0
Starting Deploy
```

Project issue reference: https://github.com/tastejs/todomvc-app-css/issues/27

**Comment by jamesward** [comment] 2017-06-13 18:29
Duplicate of #1347

**Closed by jamesward** 2017-06-13 18:29 UTC
