### ISSUE TITLE
Failed to add new bower webjar for angularjs-material v0.9.4

### ISSUE THREAD

**Issue by damnhandy** [webjars/webjars#1019] opened 2015-05-20 17:24 UTC
I am trying to add amgular-material v0.9.4 to the Bower WebJars and getting an error when trying to do so. The error I am getting is the following:

     Failed! Could not convert npm version to maven for: angular ^1.3.0 || >1.4.0-beta.0 If 
     you feel you have reached this failure in error, please file an issue:    
     https://github.com/webjars/webjars/issues

I noticed that the Bower WebJars don't have Angular 1.4.0-beta.0 available and am curious if that is the reason or if it's something else?

**Comment by jamesward** [comment] 2015-05-20 17:32
Duplicate of #1006

**Closed by jamesward** 2015-05-20 17:32 UTC
