### ISSUE TITLE
bower deploy zeroclipboard -> Application Error  

### ISSUE THREAD

**Issue by selckin** [webjars/webjars#1004] opened 2015-05-09 14:26 UTC
Following error when trying to deploy bower zeroclipboard 2.1.6 or 2.2.0

Failed! <!DOCTYPE html> <html> <head> <meta name="viewport" content="width=device-width, initial-scale=1"> <style type="text/css"> html, body, iframe { margin: 0; padding: 0; height: 100%; } iframe { display: block; width: 100%; border: none; } </style> <title>Application Error</title> </head> <body> <iframe src="//s3.amazonaws.com/heroku_pages/error.html"> <p>Application Error</p> </iframe> </body> </html> 
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  
Created WebJar 
Fetched Bower zip 
Generated POM 
Converted dependencies to Maven
 Got Bower info 
Starting Deploy

**Comment by jamesward** [comment] 2015-05-09 19:19
The problem is that their `license` (https://github.com/zeroclipboard/zeroclipboard/blob/master/bower.json#L19) points to an HTML page containing the LICENSE, not the raw text one.  And we can't determine the license from that HTML page.  I think this should be fixed upstream.

**Closed by jamesward** 2015-05-09 19:19 UTC
